function showAnswer1() {
    document.getElementById("answer1").innerHTML = "BRANCH OF SCIENCE DEALING WITH THE STUDY OF LIVING ORGANISMS.";
}

function showAnswer2() {
    document.getElementById("answer2").innerHTML = "BOTANY AND ZOOLOGY";
}
function showAnswer3() {
    document.getElementById("answer3").innerHTML = "STUDY OF PLANTS";
}
function showAnswer4() {
    document.getElementById("answer4").innerHTML = "STUDY OF ANIMALS";
}
function showAnswer5() {
    document.getElementById("answer5").innerHTML = "EXTERNAL MORPHOLOGY";
}
function showAnswer6() {
    document.getElementById("answer6").innerHTML = "ANATOMY";
}
function showAnswer7() {
    document.getElementById("answer7").innerHTML = "HISTOLOGY";
}
function showAnswer8() {
    document.getElementById("answer8").innerHTML = "CYTOLOGY";
}
function showAnswer9() {
    document.getElementById("answer9").innerHTML = "ECOLOGY";
}
function showAnswer10() {
    document.getElementById("answer10").innerHTML = "EVOLUTION";
}
function showAnswer11() {
    document.getElementById("answer11").innerHTML = "EMBRYOLOGY";
}
function showAnswer12() {
    document.getElementById("answer12").innerHTML = "ECONOMIC ZOOLOGY";
}
function showAnswer13() {
    document.getElementById("answer13").innerHTML = "TAXONOMY";
}